# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: CopyFiles@2
  inputs:
    TargetFolder: $(build.artifactstagingdirectory)
    Contents: "*.json"

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: "drop"
    PathtoPublish: $(build.artifactstagingdirectory)